## See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

# Database
db:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://:3306/zyqblog?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
  username: root
  password: root

# Hibernate
hibernate:
  dialect: org.hibernate.dialect.MySQL5Dialect
  show_sql: true
#  hbm2ddl.kpi: true
  testAccount: zs
  packagesToScan: com.zyq
  cache:
    use_second_level_cache: false
server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: frechwind
  resources:
    static-locations: classpath:/static
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 50MB
  freemarker:
    cache: false
    charset: UTF-8
    templateLoaderPath: classpath:/templates/
    suffix: .ftl
  mail:
    host: smtp.163.com
    username: leargateway
    password: lear1234
    from: leargateway@163.com
    default-encoding: UTF-8

logging:
  config: classpath:logback.xml
  path: logs
  LOG_PATH : logs

hikari:
  poolName: HikariCP
  minimumIdle: 5
  maximumPoolSize: 25
  connectionTimeout: 30000
  idleTimeout: 30000
  connectionTestQuery: SELECT 1
  #dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
  dataSourceProperties:
    ## Only for mysql
    cachePrepStmts: true
    prepStmtCacheSize: 300
    prepStmtCacheSqlLimit: 2048

haolue:
  env: prd
  hbm2ddl: true
  daoUseRedis: false

